Vagrant.configure("2") do |config|
	config.vm.box = "peru/ubuntu-18.04-server-amd64"



	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "target2Ubuntu"
	end



	config.vm.network "private_network", ip: "192.168.33.102"
	config.vm.hostname = "target2Ubuntu"



end