# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'debian/buster64'

  #config.vm.network 'forwarded_port',
  #                  guest: 80,
  #                  host: 8880,
  #                  host_ip: '127.0.0.1'

  config.vm.network 'public_network', 
					ip: '192.168.0.42'
  config.vm.provider 'virtualbox' do |vb|
    vb.gui = false
    vb.memory = '2048'
  end

  config.vm.provision 'shell', inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
    echo "PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiLz48L2hlYWQ+PGJvZHk+PGgxPkMnZXN0IGJvbiwgw6dhIGZvbmN0aW9ubmUgITwvaDE+PC9ib2R5PjwvaHRtbD4K" | base64 -d > /var/www/html/index.html
  SHELL
end