apiVersion: v1
kind: Service
metadata:
  name: mongo-srv #utilise pour la resolution DNS interne
spec: 
  type: ClusterIP
  selector:
    app: mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017