Vagrant.configure("2") do |config|
	config.vm.box = "peru/ubuntu-18.04-server-amd64"
	#config.vm.box_version = "20210501.01"



	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "target1Ubuntu"
	end



	config.vm.network "private_network", ip: "192.168.33.101"
	config.vm.hostname = "target1Ubuntu"



end