Vagrant.configure("2") do |config|
	config.vm.box = "peru/ubuntu-18.04-server-amd64"
	config.vm.box_version = "20210501.01"



	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 2
		vb.name = "master"
	end
	
	# Shared folder
	config.vm.synced_folder "vagrant-rsync/", "/home/rsync", create: true
	
	# Provisioning
	config.vm.provision :shell, :path => "provision.sh"

	config.vm.network "private_network", ip: "192.168.33.100"
	config.vm.hostname = "master"



end