Vagrant.configure("2") do |config|
	config.vm.box = "centos/7"



	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "target3Centos"
	end



	config.vm.network "private_network", ip: "192.168.33.103"
	config.vm.hostname = "target3Centos"



end